<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.gob.afirma</groupId>
		<artifactId>Integra-parent</artifactId>
		<version>2.4.0_000</version>
	</parent>
	<artifactId>Integra-encryption</artifactId>
	<name>Integra-encryption</name>
	
	<dependencies>
		<dependency>
			<groupId>es.gob.afirma</groupId>
			<artifactId>Integra-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>${version.commons.codec}</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk18on</artifactId>
		</dependency>

		<!-- Scope test -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
	</dependencies>
	
	<build>
    	<plugins>
    		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
						<manifestSection>
							<name>Dependencies</name>
							<manifestEntries>
								<Integra-commons>${version.Integra.commons}</Integra-commons>
								<commons-codec>${version.commons.codec}</commons-codec>
								<bcprov-jdk18on>${version.bouncycastle}</bcprov-jdk18on>
								<junit>${version.junit}</junit>
							</manifestEntries>
						</manifestSection>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>jar-integra-encryption</id>
						<goals>
							<goal>jar</goal>
						</goals>
						<phase>package</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${project.build.jdk}</source>
					<target>${project.build.jdk}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>