// Copyright (C) 2012-13 MINHAP, Gobierno de España
// This program is licensed and may be used, modified and redistributed under the terms
// of the European Public License (EUPL), either version 1.1 or (at your
// option) any later version as soon as they are approved by the European Commission.
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
// or implied. See the License for the specific language governing permissions and
// more details.
// You should have received a copy of the EUPL1.1 license
// along with this program; if not, you may find it at
// http://joinup.ec.europa.eu/software/page/eupl/licence-eupl

/**
 * <b>File:</b><p>es.gob.afirma.integraFacade.pojo.ServerSignerResponse.java.</p>
 * <b>Description:</b><p>Class that represents the response from the server signature service.</p>
 * <b>Project:</b><p>Library for the integration with the services of @Firma, eVisor and TS@.</p>
 * <b>Date:</b><p>17/11/2014.</p>
 * @author Gobierno de España.
 * @version 1.0, 17/11/2014.
 */
package es.gob.afirma.integraFacade.pojo;

import java.io.Serializable;

/**
 * <p>Class that represents the response from the server signature service.</p>
 * <b>Project:</b><p>Library for the integration with the services of @Firma, eVisor and TS@.</p>
 * @version 1.0, 17/11/2014.
 */
public class ServerSignerResponse implements Serializable {

    /**
     * Class serial version.
     */
    private static final long serialVersionUID = -977373345872104420L;

    /**
     * Attribute that represents the result of the process.
     */
    private Result result;

    /**
     * Attribute that represents signature format.
     */
    private String signatureFormat;

    /**
     * Attribute that represents signature identifier generated by @Firma.
     */
    private String transactionId;

    /**
     * Attribute that contains the "Asynchronous Process ID" to get the result associated with the request.
     */
    private String asyncResponse;

    /**
     * Attribute that represents the generated signature.
     */
    private byte[ ] signature;

    /**
     * Attribute that contains an updated signature.
     */
    private byte[ ] updatedSignature;

    /**
     * Constructor method for the class ServerSignerResponse.java.
     */
    public ServerSignerResponse() {
    }

    /**
     * Gets the value of the attribute {@link #result}.
     * @return the value of the attribute {@link #result}.
     */
    public final Result getResult() {
	return result;
    }

    /**
     * Sets the value of the attribute {@link #result}.
     * @param resultParam The value for the attribute {@link #result}.
     */
    public final void setResult(Result resultParam) {
	this.result = resultParam;
    }

    /**
     * Gets the value of the attribute {@link #signatureFormat}.
     * @return the value of the attribute {@link #signatureFormat}.
     */
    public final String getSignatureFormat() {
	return signatureFormat;
    }

    /**
     * Sets the value of the attribute {@link #signatureFormat}.
     * @param signatureFormatParam The value for the attribute {@link #signatureFormat}.
     */
    public final void setSignatureFormat(String signatureFormatParam) {
	this.signatureFormat = signatureFormatParam;
    }
    
    /**
     * Gets the value of the attribute {@link #transactionId}.
     * @return the value of the attribute {@link #transactionId}.
     */
    public final String getTransactionId() {
	return transactionId;
    }

    /**
     * Sets the value of the attribute {@link #transactionId}.
     * @param transactionIdParam The value for the attribute {@link #transactionId}.
     */
    public final void setTransactionId(String transactionIdParam) {
	this.transactionId = transactionIdParam;
    }

    /**
     * Gets the value of the attribute {@link #asyncResponse}.
     * @return the value of the attribute {@link #asyncResponse}.
     */
    public final String getAsyncResponse() {
	return asyncResponse;
    }

    /**
     * Sets the value of the attribute {@link #asyncResponse}.
     * @param asyncResponseParam The value for the attribute {@link #asyncResponse}.
     */
    public final void setAsyncResponse(String asyncResponseParam) {
	this.asyncResponse = asyncResponseParam;
    }

    /**
     * Gets the value of the attribute {@link #signature}.
     * @return the value of the attribute {@link #signature}.
     */
    public final byte[ ] getSignature() {
	return signature;
    }

    /**
     * Sets the value of the attribute {@link #signature}.
     * @param signatureParam The value for the attribute {@link #signature}.
     */
    public final void setSignature(byte[ ] signatureParam) {
	if (signatureParam != null) {
	    this.signature = signatureParam.clone();
	}
    }

    /**
     * Gets the value of the attribute {@link #updatedSignature}.
     * @return the value of the attribute {@link #updatedSignature}.
     */
    public final byte[ ] getUpdatedSignature() {
	return updatedSignature;
    }

    /**
     * Sets the value of the attribute {@link #updatedSignature}.
     * @param updatedSignatureParam The value for the attribute {@link #updatedSignature}.
     */
    public final void setUpdatedSignature(byte[ ] updatedSignatureParam) {
	if (updatedSignatureParam != null) {
	    this.updatedSignature = updatedSignatureParam.clone();
	}
    }

}
