<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>es.gob.afirma</groupId>
    <artifactId>Integra-parent</artifactId>
    <version>2.4.0_000</version>
  </parent>
  <artifactId>Integra-signature-report</artifactId>
  <name>Integra-signature-report</name>
  <description>Integra module for signature report generation</description>
  
	<dependencies>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>${version.log4j2}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>${version.log4j2}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-jcl</artifactId>
			<version>${version.log4j2}</version>
		</dependency>
		<dependency>
			<groupId>es.gob.afirma.lib</groupId>
			<artifactId>itext-afirma</artifactId>
			<version>${version.afirma.itext}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlgraphics</groupId>
			<artifactId>fop</artifactId>
			<version>${version.fop}</version>
		</dependency>
		<dependency>
			<groupId>net.sf.barcode4j</groupId>
			<artifactId>barcode4j-fop-ext-complete</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>xalan</groupId>
			<artifactId>xalan</artifactId>
		</dependency>
		<dependency>
        	<groupId>xalan</groupId>
        	<artifactId>serializer</artifactId>
        </dependency>

		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>core</artifactId>
			<version>3.5.3</version>
		</dependency>
		<dependency>
			<groupId>com.google.zxing</groupId>
			<artifactId>javase</artifactId>
			<version>3.5.3</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-core</artifactId>
			<version>${version.tika}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-text</artifactId>
			<version>1.12.0</version>
		</dependency>
	
		<!-- Scope test -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
		</dependency>
	</dependencies>
	
	<build>
		<resources>
			<resource>
				<directory></directory>
				<includes>
					<include>messages/*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
						</manifest>
						<manifestSection>
	                    	<name>Dependencies</name>
	                    	<manifestEntries>
	                    		<log4j-api>${version.log4j2}</log4j-api>
								<log4j-core>${version.log4j2}</log4j-core>
								<log4j-jcl>${version.log4j2}</log4j-jcl>
								<itext-afirma>${version.afirma.itext}</itext-afirma>
								<fop>${version.fop}</fop>
								<barcode4j-fop-ext-complete>2.1</barcode4j-fop-ext-complete>
								<xalan>${version.xalan}</xalan>
								<serializer>${version.xalan}</serializer>
								<zxing.core>3.5.3</zxing.core>
								<zxing.javase>3.5.3</zxing.javase>
								<version.tika>${version.tika}</version.tika>
								<commons-text>1.12.0</commons-text>
								<junit>${version.junit}</junit>
	                    	</manifestEntries>
	                    </manifestSection>
					</archive>
				</configuration>				
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${project.build.jdk}</source>
					<target>${project.build.jdk}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
